/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Compile MDX to JSX
 *
 * # Arguments
 * * `source` - MDX source code
 * * `options` - Compilation options
 *
 * # Returns
 * Returns a `CompileResult` containing the generated JSX and metadata
 *
 * # Errors
 * Returns an error if MDX compilation fails
 *
 * # Example
 * ```javascript
 * const result = compile('# Hello

This is **MDX**', {
   *   gfm: true,
   *   math: false
   * });
   * console.log(result.code);
   * ```
   */
  export declare function compile(source: string, options?: CompileOptions | undefined | null): CompileResult

/** MDX compilation options */
export interface CompileOptions {
  /** Enable GitHub Flavored Markdown */
  gfm?: boolean
  /** Enable footnotes */
  footnotes?: boolean
  /** Enable math expressions */
  math?: boolean
  /** File path for error reporting */
  filepath?: string
}

/** MDX compilation result */
export interface CompileResult {
  /** Generated JSX code */
  code: string
  /** Parsed frontmatter (if present) */
  frontmatter?: Frontmatter
  /** Collected image URLs */
  images: Array<string>
  /** Named exports */
  namedExports: Array<string>
  /** Re-exports */
  reexports: Array<string>
  /** Imports */
  imports: Array<string>
  /** Default export name */
  defaultExport?: string
}

/** Frontmatter data */
export interface Frontmatter {
  /** Raw frontmatter string */
  raw: string
  /** Parsed data as JSON string */
  data: string
}
