/**
 * # bunny-wasm
 *
 * WebAssembly bindings for bunny-mdx - compile MDX to JSX in the browser.
 *
 * This package provides TypeScript bindings for the bunny-wasm WebAssembly module,
 * allowing you to compile MDX files to JSX directly in the browser without a server.
 *
 * ## Features
 *
 * - Compile MDX to JSX in the browser
 * - Extract frontmatter (YAML/TOML)
 * - Support for GFM, math, footnotes
 * - No bundling (compile-only, WASM-compatible)
 *
 * ## Usage
 *
 * ```typescript
 * import init, { compile_mdx, WasmMdxOptions } from 'bunny-wasm';
 *
 * // Initialize WASM module
 * await init();
 *
 * // Create options
 * const options = new WasmMdxOptions();
 * options.set_gfm(true);
 * options.set_math(true);
 *
 * // Compile MDX
 * const result = compile_mdx("# Hello **World**", options);
 * console.log(result.code); // Compiled JSX
 * ```
 */

// Re-export everything from the WASM bindings
// Note: pkg/ directory is generated by wasm-pack build
export * from '../pkg/bunny_wasm.js';
// Re-export default for convenience
export { default } from '../pkg/bunny_wasm.js';

